# Generated by Django 3.1.3 on 2020-11-17 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True, verbose_name='Текст ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Тема опроса')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='описание')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата и время окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('S', 'Ответ с выбором одного варианта'), ('M', 'Ответ с выбором нескольких вариантов'), ('T', 'Ответ вводом текста')], default='S', max_length=1, verbose_name='Тип вопроса')),
                ('polling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.polling', verbose_name='Вопрос опроса')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_bool', models.BooleanField(blank=True, default=False)),
                ('answer_text', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.answer', verbose_name='ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.polling')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question')),
                ('user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question', verbose_name='Ответ вопроса'),
        ),
    ]
